Add wallpaper support for i3lock

diff --git a/bin/lock b/bin/lock
--- a/bin/lock
+++ b/bin/lock
@@ -1,32 +1,105 @@
-#!/usr/bin/env sh
+#!/bin/env bash
 
-player=0
+DISPLAY_RE="([0-9]+)x([0-9]+)\\+([0-9]+)\\+([0-9]+)"
+IMAGE_RE="([0-9]+)x([0-9]+)"
 screenshot=0
+OUTPUT_IMAGE="/tmp/i3lock.png"
+CACHE_FOLDER="/tmp/wallpapers"
 
-if [ $(command -v scrot) ] && [ $(command -v mogrify) ];then
-  screenshot=1
+if ! [ -d ${CACHE_FOLDER} ];then
+  mkdir ${CACHE_FOLDER}
 fi
 
-if [ $(command -v playerctl) ] && [ $(playerctl status) == "Playing" ];then
-  player=1
-fi
+for i in "$@"
+do
+  case $i in
+    -w=*|--wallpaper=*)
+      WALLPAPER_PATH="${i#*=}"
+      if [ ! -e "$WALLPAPER_PATH" ];then
+        echo 'Wallpaper file not found'
+        exit 1
+      fi
+      shift # past argument=value
+      ;;
+    --music)
+      MUSIC="YES"
+      shift # past argument with no value
+      ;;
+    *)
+      # unknown option
+      ;;
+  esac
+done
 
-if [ $player -eq 1 ];then
-  playerctl pause
-fi
-
-if [ $screenshot -eq 1 ];then
-  #if ! [ -f /tmp/screen_locked.png ];then
-    # Take a screenshot
-    scrot /tmp/screen_locked.png
-    # Pixellate it 10x
-    mogrify -scale 10% -scale 1000% /tmp/screen_locked.png
-  #fi
-  i3lock -i /tmp/screen_locked.png -n
+# Control the player
+if [ $(command -v playerctl) ];then
+  MUSIC_CMD="YES"
 else
-  i3lock --color 000000 -n
+  MUSIC_CMD="NO"
 fi
 
-if [ $player -eq 1 ];then
+if [ "${MUSIC_CMD}" == "YES" ] && [ "${MUSIC}" == "YES" ] && [ $(playerctl status) == "Playing" ];then
+  playerctl pause
+  MUSIC_PAUSED="YES"
+fi
+
+if [ -z "$WALLPAPER_PATH" ];then
+  if [ $(command -v scrot) ] && [ $(command -v mogrify) ];then
+    # Take a screenshot
+    scrot $OUTPUT_IMAGE
+    # Pixellate it 10x
+    mogrify -scale 10% -scale 1000% $OUTPUT_IMAGE
+    i3lock -i $OUTPUT_IMAGE -n
+  else
+    i3lock --color 000000 -n
+  fi
+else
+  MD5_BKG_IMG=$(md5sum $WALLPAPER_PATH| cut -c 1-10)
+  MD5_SCREEN_CONFIG=$(xrandr | md5sum - | cut -c 1-32)
+  LOCK_IMAGE_INFO=`identify $WALLPAPER_PATH`
+  [[ $LOCK_IMAGE_INFO =~ $IMAGE_RE ]]
+  IMAGE_WIDTH=${BASH_REMATCH[1]}
+  IMAGE_HEIGHT=${BASH_REMATCH[2]}
+  OUTPUT_IMG_WIDTH=0 # Decide size to cover all screens
+  OUTPUT_IMG_HEIGHT=0 # Decide size to cover all screens
+  OUTPUT_IMG="$CACHE_FOLDER""$MD5_SCREEN_CONFIG"."$MD5_BKG_IMG".png
+
+  #Execute xrandr to get information about the monitors:
+  while read LINE
+  do
+    #If we are reading the line that contains the position information:
+    if [[ $LINE =~ $DISPLAY_RE ]]; then
+      #Extract information and append some parameters to the ones that will be given to ImageMagick:
+      SCREEN_WIDTH=${BASH_REMATCH[1]}
+      SCREEN_HEIGHT=${BASH_REMATCH[2]}
+      SCREEN_X=${BASH_REMATCH[3]}
+      SCREEN_Y=${BASH_REMATCH[4]}
+
+      CACHE_IMG="$CACHE_FOLDER""$SCREEN_WIDTH"x"$SCREEN_HEIGHT"."$MD5_BKG_IMG".png
+
+      if [ ! -e "$CACHE_IMG" ];then
+        eval convert '$WALLPAPER_PATH' '-resize' '${SCREEN_WIDTH}X${SCREEN_HEIGHT}^' '-gravity' 'Center' '-crop' '${SCREEN_WIDTH}X${SCREEN_HEIGHT}+0+0' '+repage' '$CACHE_IMG'
+      fi
+      if (( $OUTPUT_IMG_WIDTH < $SCREEN_WIDTH+$SCREEN_X )); then OUTPUT_IMG_WIDTH=$(($SCREEN_WIDTH+$SCREEN_X)); fi;
+      if (( $OUTPUT_IMG_HEIGHT < $SCREEN_HEIGHT+$SCREEN_Y )); then OUTPUT_IMG_HEIGHT=$(( $SCREEN_HEIGHT+$SCREEN_Y )); fi;
+      PARAMS="$PARAMS $CACHE_IMG -geometry +$SCREEN_X+$SCREEN_Y -composite "
+    fi
+  done <<<"`xrandr`"
+
+  if [ ! -e $OUTPUT_IMG ]
+  then
+    eval convert -size ${OUTPUT_IMG_WIDTH}x${OUTPUT_IMG_HEIGHT} 'xc:black' $OUTPUT_IMG
+    eval convert $OUTPUT_IMG $PARAMS $OUTPUT_IMG
+  fi
+  #feh $OUTPUT_IMG
+
+  i3lock -i ${OUTPUT_IMG} -n
+fi
+
+
+#if [ ${MUSIC_CONTROL} -eq 1 ] && [ ${MUSIC} == 'YES' ] && [ $(playerctl status) == "Paused" ];then
+if [ "${MUSIC_PAUSED}" == "YES" ];then
   playerctl play
 fi
+
+exit 0
